const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const body=async r=>{try{return await r.json()}catch{return {}}};
const id=()=>crypto.randomUUID(); const now=()=>new Date().toISOString();
export default {async fetch(req,env){const u=new URL(req.url); if(!u.pathname.startsWith('/api/')) return env.ASSETS.fetch(req);
 try{
  if(u.pathname==='/api/health'&&req.method==='GET'){let a=await env.DB.prepare('SELECT COUNT(*) n FROM shared_storage').first();return J({ok:true,service:'GEMS Cloud Data Engine',version:'1.4.6',storage_items:a?.n||0,time:now()})}
  if(u.pathname==='/api/storage'&&req.method==='GET'){let keys=u.searchParams.getAll('key'),q,rs;if(keys.length){let ph=keys.map(()=>'?').join(',');rs=await env.DB.prepare(`SELECT * FROM shared_storage WHERE storage_key IN (${ph})`).bind(...keys).all()}else rs=await env.DB.prepare('SELECT * FROM shared_storage ORDER BY storage_key').all();return J({items:(rs.results||[]).map(r=>({...r,payload:JSON.parse(r.payload)}))})}
  if(u.pathname==='/api/storage'&&req.method==='POST'){let x=await body(req);if(!x.key||x.payload===undefined)return J({error:'key and payload required'},400);let old=await env.DB.prepare('SELECT * FROM shared_storage WHERE storage_key=?').bind(x.key).first(),t=now(),actor=x.actor||'DEVELOPMENT_USER',nv=1;if(old){if(x.version!=null&&Number(x.version)!==Number(old.version))return J({error:'version_conflict',current_version:old.version},409);nv=Number(old.version)+1;await env.DB.prepare('UPDATE shared_storage SET payload=?,version=?,updated_at=?,updated_by=? WHERE storage_key=?').bind(JSON.stringify(x.payload),nv,t,actor,x.key).run()}else await env.DB.prepare('INSERT INTO shared_storage(storage_key,payload,version,updated_at,updated_by) VALUES(?,?,?,?,?)').bind(x.key,JSON.stringify(x.payload),1,t,actor).run();await env.DB.prepare('INSERT INTO audit_log(id,record_id,event,module_id,form_path,actor,at,version,snapshot) VALUES(?,?,?,?,?,?,?,?,?)').bind(id(),'STORAGE:'+x.key,'SYNC',x.module_id||'SHARED',x.form_path||'shared_storage',actor,t,nv,JSON.stringify(x.payload)).run();return J({ok:true,key:x.key,version:nv,updated_at:t},old?200:201)}
  if(u.pathname==='/api/master-data'&&req.method==='GET'){let k=u.searchParams.get('kind'),rs=k?await env.DB.prepare('SELECT * FROM master_data WHERE kind=? AND active=1 ORDER BY value').bind(k).all():await env.DB.prepare('SELECT * FROM master_data WHERE active=1 ORDER BY kind,value').all();return J({items:rs.results||[]})}
  if(u.pathname==='/api/entities'&&req.method==='GET'){let k=u.searchParams.get('kind'),rs=k?await env.DB.prepare("SELECT * FROM entities WHERE status<>'DELETED' AND kind=? ORDER BY name").bind(k).all():await env.DB.prepare("SELECT * FROM entities WHERE status<>'DELETED' ORDER BY kind,name").all();return J({items:(rs.results||[]).map(r=>({...r,payload:JSON.parse(r.payload||'{}')}))})}
  if(u.pathname==='/api/audit'&&req.method==='GET'){let rid=u.searchParams.get('record_id'),rs=rid?await env.DB.prepare('SELECT * FROM audit_log WHERE record_id=? ORDER BY at DESC LIMIT 1000').bind(rid).all():await env.DB.prepare('SELECT * FROM audit_log ORDER BY at DESC LIMIT 1000').all();return J({events:rs.results||[]})}
  return J({error:'not_found'},404)
 }catch(e){return J({error:'server_error',message:String(e?.message||e)},500)} }};
